# Generated by Django 5.0.6 on 2024-08-21 09:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulkpdfdocumenttable',
            name='expirationDateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 28, 9, 11, 48, 435331, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='documentrecipientdetail',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='documenttable',
            name='email_title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='documenttable',
            name='expirationDateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 28, 9, 11, 48, 434331, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='documenttable',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='documenttable',
            name='pdfName',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='newapilog',
            name='method',
            field=models.CharField(max_length=30),
        ),
    ]
