# Generated by Django 5.0.6 on 2024-05-30 11:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documenttable',
            name='expirationDateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 6, 11, 57, 28, 313974, tzinfo=datetime.timezone.utc)),
        ),
    ]
