# Generated by Django 5.0.6 on 2024-06-08 06:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulkpdfdocumenttable',
            name='expirationDateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 15, 6, 47, 14, 500986, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='documenttable',
            name='expirationDateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 15, 6, 47, 14, 498954, tzinfo=datetime.timezone.utc)),
        ),
    ]
