# Generated by Django 5.0.6 on 2024-05-28 11:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documenttable',
            name='expirationDateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 4, 11, 58, 30, 888663, tzinfo=datetime.timezone.utc)),
        ),
    ]
