# Generated by Django 5.0.6 on 2024-06-04 10:00

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_documenttable_expirationdatetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bulkpdfpositiondata',
            name='email',
        ),
        migrations.RemoveField(
            model_name='bulkpdfpositiondata',
            name='name',
        ),
        migrations.RemoveField(
            model_name='bulkpdfpositiondata',
            name='roleId',
        ),
        migrations.AddField(
            model_name='bulkpdfdocumenttable',
            name='Schedule_type',
            field=models.CharField(default='N', max_length=1),
        ),
        migrations.AddField(
            model_name='bulkpdfdocumenttable',
            name='email_msg',
            field=models.CharField(default='Hello', max_length=500),
        ),
        migrations.AddField(
            model_name='bulkpdfdocumenttable',
            name='email_title',
            field=models.CharField(default='Hello', max_length=100),
        ),
        migrations.AddField(
            model_name='bulkpdfdocumenttable',
            name='expirationDateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 11, 10, 0, 1, 918988, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='bulkpdfdocumenttable',
            name='last_modified_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bulk_documents_last_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bulkpdfdocumenttable',
            name='last_modified_date_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='bulkpdfdocumenttable',
            name='reminderDays',
            field=models.IntegerField(default=15),
        ),
        migrations.AddField(
            model_name='bulkpdfdocumenttable',
            name='req_type',
            field=models.CharField(default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='documenttable',
            name='expirationDateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 11, 10, 0, 1, 917988, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='BulkPdfRecipientDetail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('docId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.bulkpdfdocumenttable')),
                ('roleId', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mainapp.recipientrole')),
            ],
        ),
        migrations.AddField(
            model_name='bulkpdfpositiondata',
            name='bulkpdf_recipient_detail_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mainapp.bulkpdfrecipientdetail'),
        ),
    ]
