# Generated by Django 5.0.6 on 2024-06-13 07:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_initials_initial_text_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='initials',
            name='initial_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='signature',
            name='sign_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bulkpdfdocumenttable',
            name='expirationDateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 20, 7, 8, 14, 13072, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='documenttable',
            name='expirationDateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 20, 7, 8, 14, 8591, tzinfo=datetime.timezone.utc)),
        ),
    ]
