# Generated by Django 5.0.6 on 2024-06-14 11:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_alter_bulkpdfdocumenttable_expirationdatetime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='initials',
            name='initial_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='signature',
            name='sign_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bulkpdfdocumenttable',
            name='expirationDateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 21, 11, 56, 30, 571081, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='documenttable',
            name='expirationDateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 21, 11, 56, 30, 570081, tzinfo=datetime.timezone.utc)),
        ),
    ]
