# Generated by Django 5.0.6 on 2024-06-15 07:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_initials_initial_text_signature_sign_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulkpdfdocumenttable',
            name='expirationDateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 22, 7, 12, 57, 95707, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='documenttable',
            name='expirationDateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 22, 7, 12, 57, 94706, tzinfo=datetime.timezone.utc)),
        ),
    ]
